### ISSUE TITLE
UP2 BIOS download URL need to be public

### ISSUE THREAD

**Issue by singalsu** [thesofproject/sof-docs#105]
The BIOS download URL in https://thesofproject.github.io/latest/getting_started/setup/setup_up_2_board.html need to be fixed. It's an internal Intel server. This BIOS can be used instead https://downloads.up-community.org/download/up-squared-uefi-bios-v4-0/ .

**Comment by stripes416** [comment]
I'm really confused here --- This should have been taken care of here: https://github.com/thesofproject/sof-docs/pull/99 It got merged already.

Am I misunderstanding something?

**Comment by intelkevinputnam** [comment]
@stripes416 That's on me. It's been merged, but I still need to build and publish. Taking care of it now.

**Comment by stripes416** [comment]
@intelkevinputnam I forgot manual effort was involved. Thanks for resolving it!

**Comment by intelkevinputnam** [comment]
@stripes416 Try it now. Should be updated.

**Comment by intelkevinputnam** [comment]
@singalsu Please confirm that this is fixed.

**Comment by xiulipan** [comment]
@intelkevinputnam 
I have update the Travis CI for the build.
maybe we can used it to publish.

**Comment by singalsu** [comment]
Thanks! The URL is now correct.

**Comment by singalsu** [comment]
This can be closed, the update from PR #99 is merged. Thanks @stripes416 !

**Comment by intelkevinputnam** [comment]
@xiulipan Sounds good to me.

**Comment by xiulipan** [comment]
@intelkevinputnam 
Then we may have some sync about how to do it and how to give access for the Travis.
