### ISSUE TITLE
Cherry Trail Configuration

### ISSUE THREAD

**Issue by dbogdzix** [thesofproject/sof-docs#113]
In the instruction a Cherry trail configuration is mentioned but some steps doesn't take this configuration into consideration.
Cherry trail is mentioned here:
https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/build-guide/build-from-scratch.rst#L285-L292

but those steps couldnt't be executed, because previous steps doesn't include cherry trail configuration:
https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/build-guide/build-from-scratch.rst#L186-L206

https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/build-guide/build-from-scratch.rst#L170-L173

https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/build-guide/build-from-scratch.rst#L158-L160

https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/build-guide/build-from-scratch.rst#L133-L146

**Comment by lgirdwood** [comment]
CHT == BYT wrt ISA and compiler. So everytime we say BYT we mean BYT and CHT, likewise everytime we say HSW above we also mean BDW too. e.g.
```
cmake -DTOOLCHAIN=xtensa-cht-elf -DROOT_DIR=`pwd`/../../xtensa-root/xtensa-cht-elf .. 
```
becomes
```
cmake -DTOOLCHAIN=xtensa-byt-elf -DROOT_DIR=`pwd`/../../xtensa-root/xtensa-byt-elf .. 
```
