### ISSUE TITLE
Linux kernel options

### ISSUE THREAD

**Issue by dbogdzix** [thesofproject/sof-docs#114]
I suggest to describe precisely how to execute the following snippet of instructions:
https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/build-guide/build-from-scratch.rst#L408

I wasn't able to find these options. Maybe it is unnecessary?

**Comment by lgirdwood** [comment]
@mengdonglin is there someone from kernel team who can explain the Kconfig changes. e.g. a snippet from Kconfig with SST deselected and SOF selected as modules.

@dbogdzix "Select SOF driver support and disable SST drivers." should become "Select SOF driver support and either disable Intel SST drivers or blacklist Intel SST drivers." I've supplied an example blacklist file
```
cat /etc/modprobe.d/blacklist-sst.conf 
blacklist snd_soc_sst_acpi
blacklist snd_soc_sst_dsp
blacklist snd_soc_sst_firmware
blacklist snd_soc_sst_ipc
blacklist snd_soc_sst_match
blacklist snd_soc_sst_mfld-platform
blacklist snd_soc_skl
blacklist snd_hda_intel
```

**Comment by plbossart** [comment]
this is not needed anyways if you use the recommended kconfigs.
