### ISSUE TITLE
sof-eqctl & matlab/octave scripts

### ISSUE THREAD

**Issue by dbogdzix** [thesofproject/sof-docs#115]
Sof-eqctl tool section mentions example_iir_eq.m and example_fir_eq.m scripts:

https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/effects/how-to-use-sof-eqctl-tool.rst#L68-L69

I had generated values but when I tried to use them I got error about wrong abi...

**Comment by singalsu** [comment]
Thanks for reporting this, I'll test it as well.

**Comment by singalsu** [comment]
@dbogdzix It works for me. There was in topic/sof-dev kernel an issue that the ABI check was made too eager by comparing also the minor and patch versions (those differ in current EQ blobs) but it was reverted back. Could it be that you had more than about one week old kernel?
