### ISSUE TITLE
sof-eqctl 

### ISSUE THREAD

**Issue by dbogdzix** [thesofproject/sof-docs#116]
Is there any method to determine when SOF is idle?
https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/effects/how-to-use-sof-eqctl-tool.rst#L76-L79

I couldn't get success result when executing
https://github.com/thesofproject/sof-docs/blob/c62205a564b373abfd45212de42119506c3b0da4/getting_started/effects/how-to-use-sof-eqctl-tool.rst#L85

until I reboot the OS. The instruction doesn't mention what to do if we don't get success result and what eventually could be the culprit.

**Comment by singalsu** [comment]
There's even a bug currently that happens when "sof-eqctl -s" is done during playback/capture. I'll see if I can remove this limitation from FW.

**Comment by singalsu** [comment]
This https://github.com/thesofproject/linux/issues/753

**Comment by singalsu** [comment]
@dbogdzix I created Linux PR https://github.com/thesofproject/linux/pull/890 to fix the issue. With that patch sof-eqctl also reports properly fail if DSP was busy. So there's no need to follow dmesg or sof-logger to see if the command was OK.

I will later also add to firmware feature to update EQ on-the-fly.

**Comment by lgirdwood** [comment]
@singalsu is there feature to track runtime EQ update. I'm thinking we should mark it for v1.4
