### ISSUE TITLE
Component state graph is missing INIT and SUSPEND state

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof-docs#290]
We have 6 states in https://github.com/thesofproject/sof/blob/master/src/include/sof/audio/component.h#L61

but our documents only show 4 states. Please update with states and transitions.

https://thesofproject.github.io/latest/developer_guides/firmware/components/component-overview.html#handle-the-component-device-state

Assigning to Marcin as he added all states according to git blame

**Comment by lgirdwood** [comment]
@mwasko fyi

**Comment by jajanusz** [comment]
I've added INIT to the diagram in #292 but SUSPENED is not used in FW ATM, I suspect some future-proof engineering happened here. So we will need another update later when it will be defined how transition should look actually.
