### ISSUE TITLE
update documentation for firmware installation directory

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-docs#329]
Instructions at https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#firmware-build-results to copy the firmware binary to /lib/firmware/intel/sof are out of date: on some platforms the firmware has to be copied to the community/ subdirectory of that location.

**Comment by lgirdwood** [comment]
@lyakh I think this is being resolved by @marc-hb for sof-bin - we can update after sof-bin is aligned.

**Comment by marc-hb** [comment]
The installation process has been completely redesigned and documented in https://github.com/thesofproject/sof-docs/pull/349/files. Do you think we can close this?
