### ISSUE TITLE
Is DYNAMIC_INTERRUPTS mandatory in the sof system?

### ISSUE THREAD

**Issue by hongshui3000** [thesofproject/sof-docs#340]
Is DYNAMIC_INTERRUPTS mandatory in the sof system?
I plan to call the sof library in zephyr, maybe my soc does not support dynamic interrupt.
What is the reason for the need for dynamic interrupt enable in sof? 

If CONFIG_LIBRARY is enabled, is it necessary to enable dynamic interrupts?

file : modules\audio\sof\zephyr\wrapper.c
```
/* Confirm Zephyr config settings - TODO: Use ASSERT */
#if !CONFIG_DYNAMIC_INTERRUPTS
#error Define CONFIG_DYNAMIC_INTERRUPTS
#endif
```

**Comment by lgirdwood** [comment]
@hongshui3000 still an issue ?

**Comment by lgirdwood** [comment]
@lyakh fyi

**Comment by paulstelian97** [comment]
I remember @iuliana-prodan mentioning in a private meeting that DYNAMIC_INTERRUPTS was required on NXP platforms with IRQSTEER so that the latter can work correctly.

**Comment by iuliana-prodan** [comment]
> I remember @iuliana-prodan mentioning in a private meeting that DYNAMIC_INTERRUPTS was required on NXP platforms with IRQSTEER so that the latter can work correctly.

For me is still not clear if we need DYNAMIC_INTERRUPTS or not.
For now, I've disabled them by:
```
 /* Confirm Zephyr config settings - TODO: Use ASSERT */
-#if !CONFIG_DYNAMIC_INTERRUPTS
+#if !CONFIG_IMX && !CONFIG_DYNAMIC_INTERRUPTS
 #error Define CONFIG_DYNAMIC_INTERRUPTS
 #endif
```
But, if somebody from SOF or Zephyr projects can better explain this, it will be great.
Thanks!

**Comment by lgirdwood** [comment]
IIUC, we will need need the Kconfig symbol, but once Zephyr is default this can be removed. So safe to say N.
