### ISSUE TITLE
"M_PI" does not exist

### ISSUE THREAD

**Issue by hongshui3000** [thesofproject/sof-docs#341]
When I use zephyr (minimal library) to call sof, I found that there is no definition of "M_PI".
Cause build error

I added the following code：
file:modules\audio\sof\src\math\trig.c
```
#ifndef M_PI
#define M_PI       3.14159265358979323846   // pi
#endif
```

**Comment by lgirdwood** [comment]
@hongshui3000 are these still bugs ? @lyakh has not reported any of these ?
