### ISSUE TITLE
Undefined AM_GNU_GETTEXT when building alsa-utils [WSL2 Ubuntu 20.04 LTS (Windows)]

### ISSUE THREAD

**Issue by edward-a** [thesofproject/sof-docs#352]
I am following Getting Started instructions to build SOF on WSL2 Ubuntu 20.04 LTS (Windows) and i was able to successfully compile ALSA libraries. I am however stuck on compiling alsa-utils with the following errors:

configure.ac:10: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION

Here below is the complete output after executing ./gitcompile

configure.ac:10: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:11: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
./gitcompile: line 10: gettextize: command not found
configure.ac:15: installing './compile'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
alsactl/Makefile.am: installing './depcomp'
axfer/test/Makefile.am:9: warning: source file '../container.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
axfer/test/Makefile.am:9: warning: source file '../container-riff-wave.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:9: warning: source file '../container-au.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:9: warning: source file '../container-voc.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:9: warning: source file '../container-raw.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-riff-wave.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-au.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-voc.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-raw.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../mapper.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../mapper-single.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../mapper-multiple.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
parallel-tests: installing './test-driver'
configure.ac:10: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
CFLAGS=-O2 -Wall -pipe -g
./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
./configure: line 2937: syntax error near unexpected token `external'
./configure: line 2937: `AM_GNU_GETTEXT(external)'

**Comment by lgirdwood** [comment]
@edward-a any update ?

**Comment by edward-a** [comment]
> 
> 
> Did you set the LD_LIBRARY_PATH to use the newly compiled ALSA libraries? The system ones are invariably older than the ones you need.

I tried that but it didn't help. Same error.

**Comment by edward-a** [comment]
> 
> 
> @edward-a also worth trying your local alsa libraries and utils as code is frequently upstreamed to ALSA. We do have a copy for code that is not upstream or not yet available in a ALSA release (so it's possible you have all dependencies).
> Fwiw, I dont really recommend LTS releases for desktop SW development reasons as LTS releases can fall quickly behind with developer tools / packages and become stale.

I installed a standalone version of Ubuntu 20.04.2 LTS and i am still having the same error when compiling alsa-utils:

configure.ac:10: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION

Can you please help me with the exact steps to solve this? The steps listed at https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#build-sof don't work for me. Our customer is waiting for us to port our post-processing to Chrome OS and we are stuck with this problem.

**Comment by edward-a** [comment]
Building from old Ubuntu 18.10 (the one mentioned in Getting Started) also doesn't work. Running the command below shows that none of the listed packages are available.

sudo apt-get install libgtk-3-dev libsdl1.2-dev libspice-protocol-dev \
   libspice-server-dev libusb-1.0-0-dev libusbredirhost-dev libtool-bin \
   acpica-tools valgrind texinfo virt-manager qemu-kvm \
   libvirt-daemon-system libvirt-clients virtinst libfdt-dev libssl-dev \
   pkg-config help2man gawk libncurses5 libncurses5-dev

**Comment by edward-a** [comment]
I installed gettext package:

sudo apt-get --fix-missing install gettext

Now I am having another error

**clean.c:55: undefined reference to `snd_ctl_elem_id_compare_set'**

I would really appreciate your help on this!

**Comment by edward-a** [comment]
I am now stuck at 'Toolchains'

cp config-cnl-gcc10.2-gdb9 .config
**./ct-ng build**

**Build failed in step 'Checking that gcc can statically link libstdc++ (CT_WANTS_STATIC_LINK_CXX)'**

It feels like the Getting Started section is outdated and leads you nowhere. Has anyone recently followed the steps listed there?

**Comment by lgirdwood** [comment]
@edward-a sorry you are not making good progress, I'm in GMT timezone so my replies may be delayed.

To be honest I think the other developers are all using recent distros (from 2021) and hence this is probably showing up as differences. I would recommend again using a recent distro release from this year (as this would align you with other developers).

Btw, there is now also need to build the GCC toolchain now, binaries can be downloaded from here https://github.com/thesofproject/crosstool-ng/releases/tag/gcc10.2

@ujfalusi can you comment here, you have recently started work on SOF and followed/updated the instructions. I assume the latest instructions should work on a recent distro (and maybe we need to clarify which distros to be sure on the docs) ?

**Comment by ujfalusi** [comment]
I mostly ignored all host OS related sections as they are not applicable for Artix or Gentoo Linux. I needed to install few missing packages on the way when a step failed due to missing host libraries, tools, etc.

I agree that the host side of instructions should be revisited to reflect the current LTS versions of the main distros (Fedora/ubuntu/etc) or convert them to more generic ones to be applicable to most distro?

**Comment by cjechlitschek** [comment]
> I am now stuck at 'Toolchains'
> 
> cp config-cnl-gcc10.2-gdb9 .config
> **./ct-ng build**
> 
> **Build failed in step 'Checking that gcc can statically link libstdc++ (CT_WANTS_STATIC_LINK_CXX)'**
> 
> It feels like the Getting Started section is outdated and leads you nowhere. Has anyone recently followed the steps listed there?

Ed, does it help to run the following? sudo apt-get install build-essential

**Comment by edward-a** [comment]
> 
> 
> > I am now stuck at 'Toolchains'
> > cp config-cnl-gcc10.2-gdb9 .config
> > **./ct-ng build**
> > **Build failed in step 'Checking that gcc can statically link libstdc++ (CT_WANTS_STATIC_LINK_CXX)'**
> > It feels like the Getting Started section is outdated and leads you nowhere. Has anyone recently followed the steps listed there?
> 
> Ed, does it help to run the following? sudo apt-get install build-essential

Yes, that helped, thanks! Now i am stuck with the following:

$ time for i in config*gcc10.2-gdb9; do
cp "$i" .config && ../ct-install/bin/ct-ng build || break ;
done

**bash: ../ct-install/bin/ct-ng: No such file or directory**

Here is the list of ct-ng files i found on the disk:

~/work/sof$ find -name ct-ng

**./crosstool-ng/bash-completion/ct-ng
./crosstool-ng/bin/ct-ng
./crosstool-ng/ct-ng
./crosstool-ng/share/bash-completion/completions/ct-ng**

**Comment by cjechlitschek** [comment]
you can you the ct-ng like in the step before. So the adjusted snippet is "time for i in config*gcc10.2-gdb9; do    cp "$i" .config && ./ct-ng build || break ; done"

**Comment by edward-a** [comment]
> 
> 
> you can you the ct-ng like in the step before. So the adjusted snippet is "time for i in config*gcc10.2-gdb9; do cp "$i" .config && ./ct-ng build || break ; done"

That worked. I was able to successfully build SOF.

**Comment by ujfalusi** [comment]
@edward-a, @cjechlitschek, thank you for noticing this, I have created a PR to fix the ct-ng path: #353

FYI: @lgirdwood, @marc-hb

**Comment by ujfalusi** [comment]
@edward-a, @cjechlitschek, update to mention `build-essential` as, well, essential to build SOF: #354

FYI: @lgirdwood, @marc-hb
