### ISSUE TITLE
[Platforms] Add AMD, NXP, Mediatek and Intel supported platforms to the list

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof-docs#366]
Hello Basavaraj

Please update the docs on this site with the supported AMD platform (see [this list](https://thesofproject.github.io/latest/platforms/index.html)) Thanks

**Comment by bhiregoudar** [comment]
Hi,
Thanks,
I was waiting for the driver also to get merged. What is the process to get the list updated? Should I provide the data here or need to contact someone to update the page? Please let me know.

**Comment by bhiregoudar** [comment]
I got it, I need to create a pull request with edited doc right?

**Comment by cujomalainey** [comment]
Yep that is correct :) docs are just another repo

**Comment by lgirdwood** [comment]
@kuanhsuncheng @dbaluta we are also missing new platforms from NXP and Mediatek.

**Comment by lgirdwood** [comment]
@mengdonglin @keyonjie we are missing Alderlake too.

**Comment by dbaluta** [comment]
@lgirdwood will add NXP i.MX8ULP patches after AMD patch gets merged to avoid conflicts.

**Comment by kuanhsuncheng** [comment]
@lgirdwood, 

I will discuss with my colleague and add MT8195 patches as soon as possible

**Comment by kuanhsuncheng** [comment]
create new PR https://github.com/thesofproject/sof-docs/pull/371

**Comment by dbaluta** [comment]
created PR https://github.com/thesofproject/sof-docs/pull/372 for imx8ulp

**Comment by dbaluta** [comment]
@lgirdwood @cujomalainey AMD, Mediatek and NXP platforms added to documentation page. Not sure if there is anything to be added for Intel. If all OK then we can close this PR.

**Comment by lgirdwood** [comment]
@anton-intel are you able to add Intel Alder Lake platform to this list. The specs are the same as Tigerlake, so the same row could be used. Thanks. @deb-intel fyi.

**Comment by anton-intel** [comment]
Created PR #374 to add Intel Alderlake
