### ISSUE TITLE
Clarify Docker build is just one option (was: build SOF fail with docker)

### ISSUE THREAD

**Issue by Rogety** [thesofproject/sof-docs#384]
_Transferred from `sof` to `sof-docs`, see November 18th comment below from @greg-intel_  why.

**Describe the bug**
I run ./docker-build.sh in .../sof_buiilder directory 
the mirror http://isl.gforge.inria.fr/ is down 
Then I stuck in downloading isl-0.19.tar.xz

the mirror http://isl.gforge.inria.fr/ is down 
So I change mirror https://libisl.sourceforge.io , it can work 
but the cnofig file in SOF project should be change, also.
When I git branch SOF project, the script also stuck here.  

**To Reproduce**
I follow the instructions in SOF documentation 
```
SOF_WORKSPACE=~/work/sof
mkdir -p "$SOF_WORKSPACE"
cd "$SOF_WORKSPACE"
git clone --recurse-submodules https://github.com/thesofproject/sof.git
cd "${SOF_WORKSPACE}"/sof/scripts/docker_build/sof_qemu
./docker-build.sh
cd "${SOF_WORKSPACE}"/sof/scripts/docker_build/sof_builder
./docker-build.sh <------ stuck here 
```
**Reproduction Rate**
always

**Expected behavior**
It should be work

**Impact**
I can not start my SOF project 

**Environment**

**Screenshots or console output**
```
# log 
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20211116.004925
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[ERROR]    isl: download failed
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
```
```
# relative script in Dockerfile
ARG GITHUB_SOF=https://github.com/thesofproject
ARG XT_OVERLAY_REPO=$GITHUB_SOF/xtensa-overlay.git
ARG CT_NG_REPO=$GITHUB_SOF/crosstool-ng.git
# build cross compiler
USER sof
RUN cd /home/sof && \
	git clone $CLONE_DEFAULTS --branch sof-gcc10.2 $XT_OVERLAY_REPO && \
	cd xtensa-overlay && cd ../ && \
	git clone $CLONE_DEFAULTS --branch sof-gcc10x $CT_NG_REPO && \
	mkdir -p /home/sof/work/ && \
	cd crosstool-ng && \
	./bootstrap && ./configure --prefix=`pwd` && make && make install && \
	for arch in byt hsw apl cnl imx imx8m imx8ulp rn; do \
		cp config-${arch}-gcc10.2-gdb9 .config && \
```

**Comment by marc-hb** [comment]
I think I found why the doc is confusing, it comes from a recent change https://github.com/thesofproject/sof-docs/pull/382/files Compare the doc before versus after it:

- BEFORE: https://github.com/thesofproject/sof-docs/blob/65d9f9a8~1/getting_started/build-guide/build-with-docker.rst
- AFTER: https://github.com/thesofproject/sof-docs/blob/65d9f9a8/getting_started/build-guide/build-with-docker.rst

BEFORE was EITHER pull OR build:

Building the container from DockerFile will take more than 2 hours, so we recommend using the pre-built image.
- Pull Docker image
(explain pull)
- Build Docker image
(explain build)

But AFTER now looks like a sequence.

@Rogety would you have read BEFORE differently?

@anton-intel can you please partly revert or rework your #382?

**Comment by anton-intel** [comment]
@marc-hb, @Rogety, a bullleted list indicates a user choice (either or), a numbered list - a sequence of steps.

Would the following change work better?
Add Option 1 and Option 2 to the list. Move the note about building the container to Option 2 so that it does not between the into sentence and the choices...

To easily build SOF binaries, we need a Docker image containing all of the cross-compiler and build environment dependencies. We can either build a Docker image from a DockerFile or pull an image binary from Docker Hub:

- Option 1. Pull the Docker image ...
- Option 2. Build a Docker image ...

  Note: Building the container from DockerFile will take more than 2 hours, so we recommend using the pre-built image (Option 1).

**Comment by greg-intel** [comment]
I think that's much clearer.  Labeling them with Option 1/2 implies exclusion.

**Comment by paulstelian97** [comment]
Option 1/Option 2 works. I'd have also suggested saying "Either of the following" or "Exactly one of the following" before the list.

**Comment by anton-intel** [comment]
I added PR #388 to update the topic.

**Comment by greg-intel** [comment]
Closing this issue, as the related PR #388 has been merged.
