### ISSUE TITLE
intel_debug/suggestions.html#digital-mic-issues has incorrect arecord command option

### ISSUE THREAD

**Issue by pfalcon** [thesofproject/sof-docs#467]
In the section https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#digital-mic-issues, there's a command quoted:

```
arecord -Dhw:0,6 -c4 -r48000 -sS32_LE -d 10 test.wav
```

It leads to:
```
arecord: main:668: invalid samples argument 'S32_LE'
```

Apparently, the option should be **-f**S32_LE .

**Comment by plbossart** [comment]
that's correct, feel free to send a patch :-)

**Comment by lgirdwood** [comment]
@jsarha can you take this fix. Thanks.
