### ISSUE TITLE
Mailing list dead link

### ISSUE THREAD

**Issue by jn64** [thesofproject/sof-docs#468]
On <https://thesofproject.github.io/latest/introduction/index.html#general-faq>, there is a link to <http://alsa-project.org/mailman/listinfo/sound-open-firmware> which is 404.

There is also the same link on <https://www.sofproject.org/> but not sure where to report that.

**Comment by jn64** [comment]
Aha. Seems like the postorius link is correct. Alsa wiki was updated similarly in Feb:

https://alsa-project.org/main/index.php?title=Mailing-lists&action=historysubmit&type=revision&diff=7834&oldid=7454

**Comment by cujomalainey** [comment]
Might have been caused when @perexg updated the mail server

**Comment by perexg** [comment]
I added a http redirection to the new main mailman3 page to avoid 404 errors for old mailman2 links. Thanks.
