### ISSUE TITLE
SOF build scripts update, doc update needed.

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-docs#67]
SOF build have some update. The doc need update.

**Comment by xiulipan** [comment]
Assigned myself to update the doc.

**Comment by lgirdwood** [comment]
Care to describe the updates here ?

**Comment by xiulipan** [comment]
Update details:

- soft=> sof/tools
- debug build usage
- rom build usage
- scripts usage update.
- logger ldc usage
- abi usage
And some small things, welcome to add more

**Comment by bkokoszx** [comment]
@xiulipan 
Should I help you with updating logger, ldc usage?

Btw. Logger usage is also described in tools readme file.

**Comment by bkokoszx** [comment]
Ok, so I try to update logger part : )

**Comment by xiulipan** [comment]
thanks, you can have a rump up about how to write doc in https://thesofproject.github.io/latest/howtos/process/docbuild.html

**Comment by xiulipan** [comment]
thanks, you can have a rump up about how to write doc in https://thesofproject.github.io/latest/howtos/process/docbuild.html

**Comment by xiulipan** [comment]
Change in #75
