### ISSUE TITLE
cmocka: update needed for cmocka usage

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof-docs#71]
The cmocka page is missing some detail on the commands needed to build xtensa cmocka binary and any patch/diff needed to build such a static library. Instruction for building with GCC should also be provided.

**Comment by intelkevinputnam** [comment]
@lgirdwood is there a planned PR to address this?

**Comment by jajanusz** [comment]
We may se it's resolved with #80 - Things changed meantime, now it builds automatically, so unless user wants to compile some prebuilt lib to speed up things he needs to know nothing about cmocka. Ofc we can always make some verbose documentation about that process, but it's not needed to use it.

**Comment by jajanusz** [comment]
@intelkevinputnam @lgirdwood 
Can one of you close it please?

**Comment by lgirdwood** [comment]
@jajanusz I think we need the verbose docs on how users can build cmocka for xtensa locally.

**Comment by jajanusz** [comment]
> @jajanusz I think we need the verbose docs on how users can build cmocka for xtensa locally.

Then it'll be more *educational* article than *how-to*, because it's like ~1 command with our fork: https://github.com/thesofproject/sof/blob/master/test/cmocka/CMakeLists.txt#L13-L26
:smirk:

**Comment by lgirdwood** [comment]
@jajanusz ok sounds good :)

**Comment by jajanusz** [comment]
@lgirdwood Can we close it or need something more?
