### ISSUE TITLE
there is not a script named build-soft.sh

### ISSUE THREAD

**Issue by amerysong** [thesofproject/sof-docs#72]
In the ***Build SOF from scratch*** Chapter, ***Build topology and tools*** section, we should run *build-soft.sh*, but there is no such script in the sof repo.

**Comment by fredoh9** [comment]
SOFT is depreciated recently and merged into SOF project. You can build SOFT tool in SOF project. 
$ cd ~/work/sof/sof/
$ ./scripts/build-soft.sh

I will update the document and start pull request in a day or two.

**Comment by xiulipan** [comment]
Please refer #67 
Doc will be updated soon.

**Comment by intelkevinputnam** [comment]
@xiulipan can you confirm that this issue is resolved.

**Comment by xiulipan** [comment]
@intelkevinputnam 
Please close this issue. The docs have updated as well as the scripts.
