### ISSUE TITLE
remove the prompt in all bash examples

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-docs#86]
Make sure people can just copy/paste instructions in a terminal window for all bash examples

Instructions such as
````bash
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install gcc-7 g++-7
$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
````
should really be 

````bash
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-7 g++-7
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
````

**Comment by intelkevinputnam** [comment]
Good point. Totally agree.

**Comment by stripes416** [comment]
Could I take this issue? I don't seem to be able to assign it to myself at the moment.

**Comment by intelkevinputnam** [comment]
@stripes416 You've got it. :)

**Comment by stripes416** [comment]
Thanks @intelkevinputnam!

**Comment by plbossart** [comment]
> Could I take this issue? I don't seem to be able to assign it to 
> myself at the moment.
>
In addition to the fix of the documentation, we should have a matching 
script that does everything for you. Instructions are always broken for 
months before people bother to report them, a broken script will trigger 
more reports.

The hard-coded paths should go away, e.g. ~/work/sof should be replaced 
by a variable that can be easily adjusted.

Thanks

-Pierre

**Comment by lgirdwood** [comment]
@stripes416 whilst you are updating docs the following steps also need rectified

1) Building xtensa-newlib needs a
```
rm -fr rm etc/config.cache
```
after make install and before configure of next target.

2)  The install deps are different for Ubuntu 18.10 compared to Ubuntu 18.4 (documented). + flex bison - kvm e.g.
```
udo apt-get install libgtk-3-dev libsdl-dev libspice-protocol-dev libspice-server-dev libusb-1.0-0-dev libusbredirhost-dev                      libtool-bin iasl valgrind texinfo virt-manager virtinst libfdt-dev libssl-dev pkg-config                      help2man gawk libncurses5 libncurses5-dev flex bison
```

**Comment by stripes416** [comment]
@plbossart @intelkevinputnam Do either of you have a suggestion / opinion on how we should handle situations like:
```diff
 .. code-block:: bash
 
-   $ ls builds/
+   ls builds/
    xtensa-apl-elf          xtensa-byt-elf          xtensa-cnl-elf          xtensa-hsw-elf
-   $ cp -r builds/* ~/work/sof/
+   cp -r builds/* ~/work/sof
```
(starting at line 143 in getting_started/build-guide/build-from-scratch.rst)

where removing the '$' puts the command at the same indentation as the expected output?

**Comment by intelkevinputnam** [comment]
@stripes416 I can think of 2 ways of addressing it:

1. Add "#" characters to turn output into comments in a bash script
2. Use separate code blocks for input and output: ".. code-block:: bash" for input and ".. code-block:: console" for output.

**Comment by intelkevinputnam** [comment]
@plbossart I actually have a script that will pull all of the ".. code-block:: bash" sections from a .rst document and output to stdout.  I agree about using variables, and I'd suggest starting the instructions for a series of steps by defining the variables that will be used later on in the instructions to make the resulting bash script easier to use.

**Comment by stripes416** [comment]
@plbossart @lgirdwood Speaking of incorrect instructions -- After the[ alsa-lib](https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#build-alsa-lib-and-alsa-utils) instructions, the docs say to:

> Update an environment variable to refer to the alsa-lib with the one we just built.
```bash
export LD_LIBRARY_PATH=~/work/sof/alsa-lib/src/.libs:$LD_LIBRARY_PATH
```
However when building the cross compiler for the various platforms, running `./ct-ng build` will give this error:

```bash
46         stripes416@system:~/projects/sof/crosstool-ng$ ./ct-ng build
47         [INFO ]  Performing some trivial sanity checks
48         [ERROR]  Don't set LD_LIBRARY_PATH. It screws up the build.
```
If the `export LD_LIBRARY_PATH` is left out, it seems to work fine. Is this something we want to remove, or do we need to try to rework ct-ng?

**Comment by stripes416** [comment]
Do we agree this issue is closed? I can't close it myself.
