### ISSUE TITLE
build-from-scratch instructions incorrect

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-docs#87]
the following instructions are incorrect
````
#Baytrail
$ ./configure --target=xtensa-byt-elf --prefix=/home/$USER/work/sof/xtensa-root
$ make
$ make install
#Haswell
$ ./configure --target=xtensa-hsw-elf --prefix=/home/$USER/work/sof/xtensa-root
$ make
$ make install
#Apollo Lake
$ ./configure --target=xtensa-apl-elf --prefix=/home/$USER/work/sof/xtensa-root
$ make
$ make install
#Cannon Lake
$ ./configure --target=xtensa-cnl-elf --prefix=/home/$USER/work/sof/xtensa-root
$ make
$ make install
````
it's necessary to do a 
````
rm etc/config.cache
````
 between platforms

**Comment by lgirdwood** [comment]
@plbossart not sure why you are seeing this as autotools should be gone ?

**Comment by jajanusz** [comment]
@lgirdwood 
I guess these are listing for building toolchains: https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#build-toolchain-from-source

**Comment by lgirdwood** [comment]
@plbossart got it, it's not for FW but for xtensa-newlib. Can reproduce

**Comment by xiulipan** [comment]
@lgirdwood @plbossart 
For Docker, there is a make clean to avoid conflict. If the `rm etc/config.cache` can solve the issue. I can make a fix for that.

**Comment by lgirdwood** [comment]
Now fixed in the docs by @stripes416
