### ISSUE TITLE
Add a free to use license for presentations

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/sof-docs#91]
This will allow users to use parts / images from the presentations found here:

https://github.com/thesofproject/sof-docs/tree/master/presentations

**Comment by lgirdwood** [comment]
@intelkevinputnam is this something you can help with. It should be a free and permissive license for the slide and any documentation.

**Comment by lgirdwood** [comment]
@intelkevinputnam sounds good to me.

**Comment by intelkevinputnam** [comment]
OK. I've updated the LICENSE file in the root directory to reflect this. We can think about if/where we might want to put this info in the documentation itself.

**Comment by dbaluta** [comment]
@intelkevinputnam  @lgirdwood Thanks!
